name: Sync and test rolling

on:
  schedule:
    - cron: "0 9 * * 1"
  workflow_dispatch:
    inputs:
      target-branch:
        description: "Target branch to create/update"
        required: false
        default: "bump-rolling"
        type: string
      upstream-ref:
        description: "Upstream nixpkgs ref to sync from"
        required: false
        default: "nixpkgs-unstable"
        type: string

permissions:
  actions: write # Trigger workflows
  contents: write # Push commits

jobs:
  fetch-and-patch:
    uses: ./.github/workflows/fetch-and-patch.yml
    with:
      target-branch: ${{ inputs.target-branch || 'bump-rolling' }}
      upstream-ref: ${{ inputs.upstream-ref || 'nixpkgs-unstable' }}

  run-tests:
    needs: fetch-and-patch
    uses: ./.github/workflows/run-devenv-tests.yml
    with:
      nixpkgs-input: "github:cachix/devenv-nixpkgs/${{ inputs.target-branch || 'bump-rolling' }}"
    secrets: inherit